import {
  Bell,
  CalendarDays,
  Clock,
  FileText,
  Globe,
  HelpCircle,
  History,
  Layers,
  LayoutDashboard,
  LayoutTemplate,
  Megaphone,
  MegaphoneIcon,
  MessageSquareText,
  Navigation,
  Percent,
  Settings,
  Shield,
  ShieldMinus,
  Sparkles,
  Star,
  Tag,
  UserCheck,
  Users,
  Wallet,
} from "lucide-react";

export const AdminNavList = [
  {
    label: "Dashboard",
    id: "dashboard",
    icon: LayoutDashboard,
    link: "/dashboard",
  },
  {
    label: "Customers",
    id: "customer",
    icon: Users,
    link: "/customer",
    badge: "48.2k",
  },

  {
    label: "Providers",
    id: "providers",
    icon: UserCheck,
    badge: "1 Pending",
    link: "/provider",
  },
  {
    label: "Bookings",
    id: "booking",
    icon: CalendarDays,
    link: "/booking",
    badge: "642 Today",
  },

  {
    label: "Global Locations",
    id: "globalLocation",
    link: "/location",
    icon: Globe,
  },
  {
    label: "Live Tracking",
    id: "liveTracking",
    icon: Navigation,
    link: "/live-tracking",
  },
  {
    label: "Categories",
    id: "categories",
    icon: Layers,
    link: "/categorys",
  },
  {
    label: "Pricing Config",
    id: "pricingConfig",
    link: "/commission",
    icon: Tag,
  },

  {
    label: "Time Slots",
    id: "timeSlots",
    link: "/time-slots",
    icon: Clock,
  },
  {
    label: "Payments & Payouts",
    id: "paymentPayouts",
    link: "/payment-payouts",
    icon: Wallet,
  },
  {
    label: "Page & Form Builder",
    id: "pageBuilder",
    icon: LayoutTemplate,
    link: "/page-build",
  },
  {
    label: "Notifications",
    id: "notifications",
    icon: Bell,
    link: "/notifications",
  },
  {
    label: "Commission",
    id: "commission",
    icon: Percent,
    link: "/pricing",
  },
  {
    label: "AI Analytics",
    id: "aI_Analytics",
    icon: Sparkles,
    link: "/ai-analytics",
  },
  {
    label: "Reports",
    id: "reports",
    icon: FileText,
    link: "/reports",
  },
  {
    label: "Reviews",
    id: "reviews",
    icon: Star,
    link: "/reviews",
  },
  {
    label: "Support_Disputes",
    id: "support_Disputes",
    icon: HelpCircle,
    link: "/help-center",
    badge: "1 High",
  },
  {
    label: "Marketing",
    id: "marketing",
    icon: MegaphoneIcon,
    link: "/marketing",
  },
  {
    label: "RBAC & Employees",
    id: "rbac_Employees",
    icon: Shield,
    link: "/rbac-employees",
  },
  {
    label: "Audit Logs",
    id: "audit_Logs",
    icon: History,
    link: "/history",
  },
  {
    label: "Settings",
    id: "/settings",
    icon: Settings,
    link: "/settings",
  },
];
